### ISSUE TITLE
newrecovered shows as 0

### ISSUE THREAD

**Issue by sa9St** [MordechaiHadad/Covid19.NET#1]
when used to call newrecovered it returns 0

**Comment by MordechaiHadad** [comment]
hi this is not an issue it just says that there are no new recovered cases.
you can look here in the API: https://api.covid19api.com/summary

**Comment by sa9St** [comment]
but it's shown here https://covid19.moh.gov.sa/

**Comment by MordechaiHadad** [comment]
> 
> 
> but it's shown here https://covid19.moh.gov.sa/

The API might be outdated by a bit about saudi arabia, which is something I can't do...
This is a wrapper for the API, not the API.
